apiVersion: v1
kind: Service
metadata:
  name: cat-service
spec:
  selector:
    app: cat
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat
  labels:
    app: cat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cat
  template:
    metadata:
      labels:
        app: cat
    spec:
      containers:
      - name: cat
        image: murcagr/cat-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
