apiVersion: v1
kind: Service
metadata:
  name: food-service
spec:
  selector:
    app: food
  ports:
    - protocol: TCP
      port: 5053
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: food
  labels:
    app: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food
  template:
    metadata:
      labels:
        app: food
    spec:
      containers:
      - name: food
        image: murcagr/food-service:latest
        ports:
        - containerPort: 80