apiVersion: v1
kind: Service
metadata:
  name: api-gw
spec:
  selector:
    app: gw
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30049

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw
  labels:
    app: gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gw
  template:
    metadata:
      labels:
        app: gw
    spec:
      containers:
      - name: gw
        image: murcagr/api-gateway:latest
        ports:
        - containerPort: 80
      nodeSelector:
        expo: yep
