apiVersion: v1
kind: Service
metadata:
  name: owner-service
spec:
  selector:
    app: owner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: owner
  labels:
    app: owner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: owner
  template:
    metadata:
      labels:
        app: owner
    spec:
      containers:
      - name: owner
        image: murcagr/owner-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
