apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  type: NodePort
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 80
      nodePort: 30010

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: murcagr/user-api:latest
        ports:
        - containerPort: 80
      nodeSelector:
        expo: yep 